challenge_ideas = [
# --- Daily Life / Personal Vlogs ---
"Document your morning routine",
"Film a day in your life",
"Record your night routine",
"Show your commute to school/work",
"Film a weekend in your life",
"Record what you eat in a day",
"Show your workspace or room",
"Film a 24-hour day recap",
"Vlog your chores or cleaning routine",
"Document a random day with no plan",

# --- Fun / Random Activities ---
"Try a day speaking only in questions",
"Record yourself doing a fun challenge",
"Film a reaction to something new",
"Do a 1-minute dance in public",
"Try a silly outfit change vlog",
"Record a random act of kindness",
"Vlog a spontaneous adventure",
"Do a 'surprise someone' vlog",
"Film a funny pet moment",
"Record a random funny conversation (with consent)",

# --- Outdoors / Nature ---
"Film a sunrise or sunset",
"Document a walk in your neighborhood",
"Record a trip to a local park",
"Vlog at a beach or lake",
"Capture street life in your town",
"Film nature sounds for a minute",
"Record clouds or weather changes",
"Film a scenic drive",
"Vlog a hike or nature trail",
"Record a night sky or stars",

# --- Friends / Social Vlogs ---
"Film a meetup with friends",
"Do a short group challenge",
"Record a day hanging out at a café",
"Vlog a fun outing or trip",
"Capture candid moments with friends",
"Film a group game session",
"Record a surprise for a friend",
"Film a funny group activity",
"Do a friendship Q&A vlog",
"Capture a mini celebration",

# --- Self / Reflection ---
"Film a 1-minute gratitude vlog",
"Record a thought or feeling you had today",
"Vlog a personal goal for the week",
"Record a reflection on a recent event",
"Film your favorite quiet place",
"Do a 'this week in my life' vlog",
"Record something that inspires you",
"Vlog a meaningful moment today",
"Film your emotions in a short montage",
"Capture your personal routine in a new way",

# --- Creative / Artistic ---
"Record a 1-minute story without talking",
"Film a day using only one color theme",
"Do a silent vlog for one day",
"Record a day using only POV shots",
"Film a continuous take for 1-2 minutes",
"Capture motion in your environment creatively",
"Film from unusual angles",
"Record a short cinematic scene in your room",
"Vlog your surroundings with only background sounds",
"Make a mood-focused short video",

# --- Food / Daily Life Mini-Vlogs ---
"Vlog making or eating breakfast",
"Record a snack review",
"Film a coffee or tea moment",
"Vlog a visit to a market or store",
"Record a lunch or dinner outing",
"Film a favorite treat",
"Vlog your grocery haul creatively",
"Record cooking with fun edits (without tutorial)",
"Capture a favorite meal visually",
"Film a food challenge with friends",

# --- Miscellaneous / Random Fun ---
"Vlog a random public place (with permission)",
"Record a day in 10 short clips",
"Film your favorite hobby without explaining it",
"Record your surroundings from morning to night",
"Vlog a one-minute funny montage",
"Capture the sounds of your day",
"Film a random act of kindness",
"Record a silly moment or prank (safe!)",
"Film reflections in a mirror creatively",
"Vlog with a specific theme for the day",

# --- Travel / Exploration ---
"Vlog a local street you never visited",
"Record a park or outdoor space",
"Film a day trip to a nearby town",
"Capture city streets and people",
"Vlog a ride on public transport",
"Film a scenic drive or bike ride",
"Record a new cafe or shop",
"Vlog a short travel experience",
"Film the sunset at a landmark",
"Record a mini cultural experience",

# --- Week-in-Life / Compilation Vlogs ---
"Record short clips throughout the week and compile",
"Vlog highlights of your week",
"Film moments that made you smile this week",
"Record challenges you faced this week",
"Vlog funny or awkward moments",
"Film daily routines with slight variations",
"Record favorite moments from school/work",
"Vlog personal achievements",
"Film interesting people you see (with permission)",
"Compile short clips of weather changes",

# --- Pet / Animal Focused ---
"Vlog a day with your pet",
"Record pet reactions to something new",
"Film a walk with your pet",
"Record a funny moment of your pet",
"Vlog pet feeding or playing",
"Film a pet doing tricks",
"Capture your pet’s expressions",
"Record a pet’s first reaction to something",
"Vlog a day from your pet’s POV (fun angles)",
"Film your pet interacting with the environment",

# --- Creative Visuals / Storytelling ---
"Film a short story in 30 seconds",
"Record a day as a mini documentary",
"Vlog with only close-up shots",
"Film shadows and silhouettes creatively",
"Record a motion-focused video (walking, running, etc.)",
"Vlog an object-focused story",
"Film a ‘time-lapse’ of something",
"Record a 1-minute suspense scene",
"Film reflections and mirrors creatively",
"Vlog using only natural light for effect",

# --- Mood / Atmospheric ---
"Record rain falling outside",
"Vlog a cozy moment at home",
"Film a sunrise or sunset from window",
"Capture city lights at night",
"Vlog quiet moments of reflection",
"Record wind, leaves, or movement",
"Film your favorite peaceful spot",
"Vlog a candlelit or evening scene",
"Capture shadows creatively",
"Film a chill day montage",

# --- Random / Fun Mini-Challenges ---
"Vlog yourself doing a silly dance",
"Record your reflection in multiple surfaces",
"Film random street patterns",
"Vlog an impromptu performance",
"Record a short funny moment with friends",
"Film only your hands doing something",
"Vlog with only POV shots for a minute",
"Record a challenge using props around you",
"Film a day in 5-second clips",
"Vlog a 'silent comedy' moment",

# --- Misc / Miscellaneous ---
"Record random people (with permission) doing something interesting",
"Film your favorite outdoor spot",
"Vlog your city at a random time",
"Record a montage of something repetitive (e.g., walking)",
"Film a short story from objects",
"Vlog the sounds of your home",
"Record your day from different perspectives",
"Film a mini story using only two objects",
"Vlog something that surprised you today",
"Record an everyday thing creatively",
# Continue adding until you reach 250
]
